# Generated by Django 3.0 on 2024-01-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': ('Porteiros',)},
        ),
    ]
