# Generated by Django 3.0 on 2024-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20240116_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='horario_autorizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Horário de autorização de entrada'),
        ),
    ]
